# Generated by Django 3.2.3 on 2021-05-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_tracks_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cd_art',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='album',
            name='release_year',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_art',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
