# Generated by Django 3.2.3 on 2021-05-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210524_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cd_art',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_art',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
