# Generated by Django 3.2.3 on 2021-05-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210525_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_no',
            field=models.IntegerField(),
        ),
    ]
